server:
  port: 8081
spring:
  application:
    name: test
cloud:
  config:
    server:
      git:
        uri: https://github.com/xuguangwu/spring-cloud-learning.git
        search-paths: configFiles